# Generated by Django 4.2.22 on 2025-06-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches_in_charge', to='individual.individual'),
        ),
        migrations.AlterUniqueTogether(
            name='userchurch',
            unique_together={('user', 'church')},
        ),
    ]
