# Generated by Django 4.2.22 on 2025-06-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterField(
            model_name='church',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserChurch',
        ),
    ]
