# Generated by Django 4.2.23 on 2025-06-19 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('member_list', 'Member List'), ('contribution', 'Contribution Report'), ('family', 'Family Report'), ('deceased', 'Deceased Members'), ('inactive', 'Inactive Members'), ('custom', 'Custom Report')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='church.church')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Log',
                'verbose_name_plural': 'Report Logs',
            },
        ),
    ]
