# Generated by Django 4.2.23 on 2025-06-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(blank=True, help_text='Ang pangunang indibidwal nga nagrepresentar sa pamilya (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='individual.individual'),
        ),
    ]
