# Generated by Django 4.2.22 on 2025-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
        ('church', '0003_alter_church_options_alter_church_in_charge_and_more'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={},
        ),
        migrations.AddField(
            model_name='family',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_managed', to='individual.individual'),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='church.church'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=255),
        ),
    ]
