# Generated by Django 4.2.23 on 2025-06-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
        ('family', '0001_initial'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familymembership', to='individual.individual', verbose_name='Individual Member'),
        ),
        migrations.AddField(
            model_name='family',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='church.church', verbose_name='Affiliated Church'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'individual')},
        ),
    ]
