# Generated by Django 4.2.23 on 2025-06-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_managed', to='individual.individual'),
        ),
    ]
