# Generated by Django 4.2.23 on 2025-06-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
        ('church', '0001_initial'),
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='description',
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='individual.individual', verbose_name='Head of Family'),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Family Address'),
        ),
        migrations.AlterField(
            model_name='family',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='church.church', verbose_name='Associated Church'),
        ),
        migrations.AlterField(
            model_name='family',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='family',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
