# Generated by Django 4.2.23 on 2025-06-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['family_name'], 'verbose_name_plural': 'Families'},
        ),
        migrations.RemoveField(
            model_name='family',
            name='in_charge',
        ),
        migrations.AddField(
            model_name='family',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(blank=True, help_text='Ang pangunang indibidwal nga nagrepresentar sa pamilya (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='individual.individual'),
        ),
    ]
