# Generated by Django 4.2.22 on 2025-06-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('corporate', 'Corporate'), ('cupcake', 'Cupcake'), ('bumblebee', 'Bumblebee'), ('emerald', 'Emerald'), ('synthwave', 'Synthwave'), ('retro', 'Retro'), ('garden', 'Garden'), ('business', 'Business'), ('night', 'Night')], default='corporate', help_text='Choose your preferred color theme for the application.', max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload your profile picture (optional).', null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='UserChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User Church Assignment',
                'verbose_name_plural': 'User Church Assignments',
            },
        ),
    ]
