# Generated by Django 4.2.23 on 2025-06-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('IN_CHARGE', 'In-Charge'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
