# Generated by Django 4.2.23 on 2025-06-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userchurch',
            options={'ordering': ['user__username', 'church__name'], 'verbose_name': 'User Church Assignment', 'verbose_name_plural': 'User Church Assignments'},
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='church_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='church.church', verbose_name='Assigned Church'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Profile Active?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('IN_CHARGE', 'In-Charge'), ('USER', 'User')], default='USER', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light (Default DaisyUI)'), ('dark', 'Dark'), ('corporate', 'Corporate'), ('retro', 'Retro'), ('cyberpunk', 'Cyberpunk'), ('valentine', 'Valentine'), ('halloween', 'Halloween'), ('forest', 'Forest'), ('aqua', 'Aqua'), ('luxury', 'Luxury'), ('dracula', 'Dracula'), ('cmyk', 'CMYK'), ('autumn', 'Autumn'), ('business', 'Business'), ('acid', 'Acid'), ('lemonade', 'Lemonade'), ('night', 'Night'), ('coffee', 'Coffee'), ('winter', 'Winter'), ('dim', 'Dim'), ('nord', 'Nord'), ('sunset', 'Sunset')], default='corporate', max_length=50, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchurch',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users_via_link', to='church.church', verbose_name='Assigned Church'),
        ),
        migrations.AlterField(
            model_name='userchurch',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_church_link', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
