# Generated by Django 4.2.23 on 2025-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='ACTIVE', max_length=150),
        ),
        migrations.AlterField(
            model_name='individual',
            name='relationship',
            field=models.CharField(choices=[('HEAD', 'Head'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
