# Generated by Django 4.2.23 on 2025-06-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='church.church'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='membership_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
