# Generated by Django 4.2.22 on 2025-06-09 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_family_options_family_in_charge_and_more'),
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name_plural': 'Individuals'},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='mobile_number',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='church',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='email',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='members_serial',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='photo',
        ),
        migrations.AddField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced'), ('P', 'Separated')], default='S', help_text='The civil status of the individual.', max_length=1),
        ),
        migrations.AddField(
            model_name='individual',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='The biological sex of the individual.', max_length=1),
        ),
        migrations.AddField(
            model_name='individual',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.family'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='relationship',
            field=models.CharField(choices=[('HEAD', 'Head of Family'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('OTHER', 'Other Relative')], default='CHILD', help_text='Relationship to the head of the family.', max_length=10),
        ),
    ]
