# Generated by Django 4.2.23 on 2025-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_alter_individual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='membership_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
