# Generated by Django 4.2.23 on 2025-06-19 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_individual_church_alter_individual_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='membership_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
