# Generated by Django 4.2.23 on 2025-06-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution_type', '0001_initial'),
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('date_paid', models.DateField(verbose_name='Date Paid')),
                ('or_number', models.CharField(max_length=50, unique=True, verbose_name='Official Receipt Number')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'G-Cash')], max_length=10, verbose_name='Payment Method')),
                ('gcash_reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='G-Cash Reference No.')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Is G-Cash Validated?')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=10, verbose_name='Payment Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks/Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL, verbose_name='Collected By')),
                ('contribution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_by_type', to='contribution_type.contributiontype', verbose_name='Contribution Type')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_payer', to='individual.individual', verbose_name='Payer')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date_paid', 'or_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCoveredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_covered', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Covered for Individual')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks for this Individual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_members_created', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_covered', to='individual.individual', verbose_name='Covered Individual')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='payment.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Covered Member',
                'verbose_name_plural': 'Payment Covered Members',
                'ordering': ['payment__or_number', 'individual__surname'],
                'unique_together': {('payment', 'individual')},
            },
        ),
    ]
