# Generated by Django 4.2.23 on 2025-06-13 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online Payment'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.contributiontype')),
                ('covered_members', models.ManyToManyField(blank=True, help_text='Select members covered by this payment.', related_name='payments_covered', to='individual.individual')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='individual.individual', verbose_name='Payee')),
            ],
            options={
                'verbose_name': 'Payment/Contribution',
                'verbose_name_plural': 'Payments/Contributions',
                'ordering': ['-date_paid', '-created_at'],
            },
        ),
    ]
