# Generated by Django 4.2.23 on 2025-06-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Contribution Type',
                'verbose_name_plural': 'Contribution Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_paid', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash')], default='CASH', max_length=10)),
                ('gcash_reference_number', models.CharField(blank=True, help_text='Required if Payment Method is GCash', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING_VALIDATION', 'Pending Validation'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_legacy_record', models.BooleanField(default=False, help_text='Indicates if this is a record imported from an old system.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, help_text='Church where payment was collected or associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.church')),
                ('collected_by', models.ForeignKey(help_text='User who collected the payment (Cashier/InCharge)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL)),
                ('contribution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.contributiontype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('deceased_member', models.ForeignKey(blank=True, help_text='If this payment is related to a deceased member (e.g., Mortuary Aid).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_for_deceased', to='individual.individual')),
                ('individual', models.ForeignKey(blank=True, help_text='The individual who made the payment (if not covered by another)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made_by_self', to='individual.individual')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='Admin who validated GCash payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By (Admin Only)')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ['-date_paid', '-receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='CoveredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0.0, help_text="Amount from this payment specifically allocated to this member's account.", max_digits=10)),
                ('notes', models.TextField(blank=True, help_text="Specific notes for this member's coverage in this payment.", null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_covered', to='individual.individual')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Covered Member',
                'verbose_name_plural': 'Covered Members',
                'unique_together': {('payment', 'individual')},
            },
        ),
    ]
