# Generated by Django 4.2.23 on 2025-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='series_prefix',
        ),
        migrations.AddField(
            model_name='payment',
            name='gcash_reference_number',
            field=models.CharField(blank=True, help_text='Reference number for GCash transactions (e.g., transaction ID).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Official Receipt (OR) number or internal reference. Auto-generated for new payments (YY-NNNN format).', max_length=100, null=True),
        ),
    ]
