# Generated by Django 4.2.23 on 2025-06-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0.0, help_text="Amount from this payment specifically allocated to this member's account.", max_digits=10)),
                ('notes', models.TextField(blank=True, help_text="Specific notes for this member's coverage in this payment.", null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_covered', to='individual.individual')),
            ],
            options={
                'verbose_name': 'Covered Member',
                'verbose_name_plural': 'Covered Members',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-receipt_number'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='covered_members',
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='church',
            field=models.ForeignKey(blank=True, help_text='Church where payment was collected or associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.church'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(help_text='User who collected the payment (Cashier/InCharge)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contribution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.contributiontype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deceased_member',
            field=models.ForeignKey(blank=True, help_text='If this payment is related to a deceased member (e.g., Mortuary Aid).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_for_deceased', to='individual.individual'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gcash_reference_number',
            field=models.CharField(blank=True, help_text='Required if Payment Method is GCash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='The individual who made the payment (if not covered by another)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made_by_self', to='individual.individual'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_legacy_record',
            field=models.BooleanField(default=False, help_text='Indicates if this is a record imported from an old system.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING_VALIDATION', 'Pending Validation'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(db_index=True, default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who validated GCash payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By (Admin Only)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Payee',
        ),
        migrations.AddField(
            model_name='coveredmember',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='payment.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='coveredmember',
            unique_together={('payment', 'individual')},
        ),
    ]
