# Generated by Django 4.2.23 on 2025-06-23 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Cancelled'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Validated'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='User who validated the payment (e.g., for GCash)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By'),
        ),
    ]
