# Generated by Django 4.2.23 on 2025-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentindividualallocation',
            name='is_payer',
            field=models.BooleanField(default=False, help_text='True if this individual is the actual payer of this allocated amount.'),
        ),
    ]
