# Generated by Django 4.2.23 on 2025-06-15 07:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-created_at'], 'verbose_name': 'Payment/Contribution', 'verbose_name_plural': 'Payment/Contributions'},
        ),
        migrations.AddField(
            model_name='payment',
            name='cancellation_remarks',
            field=models.TextField(blank=True, help_text='Reason for cancellation, if applicable.', null=True, verbose_name='Cancellation Remarks'),
        ),
        migrations.AddField(
            model_name='payment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Edited Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_encoded', to=settings.AUTH_USER_MODEL, verbose_name='Encoded By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encoded_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0), verbose_name='Encoded Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Check if this payment record has been cancelled.', verbose_name='Is Cancelled?'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_serial_number',
            field=models.CharField(blank=True, help_text='Automatically generated unique receipt serial number.', max_length=100, null=True, unique=True, verbose_name='System Receipt No.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALIDATED', 'Validated'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the payment (e.g., Pending, Validated, Cancelled).', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validated Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
