# Generated by Django 4.2.23 on 2025-06-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individual', '0001_initial'),
        ('church', '0001_initial'),
        ('payment', '0002_alter_payment_options_remove_payment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-or_number'], 'verbose_name': 'Payment Record', 'verbose_name_plural': 'Payment Records'},
        ),
        migrations.RemoveField(
            model_name='coveredmember',
            name='amount_allocated',
        ),
        migrations.RemoveField(
            model_name='coveredmember',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cancellation_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='validation_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Notes'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validated At'),
        ),
        migrations.AlterField(
            model_name='coveredmember',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individual'),
        ),
        migrations.AlterField(
            model_name='coveredmember',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='church.church', verbose_name='Assigned Church'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contribution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contribution_type.contributiontype', verbose_name='Contribution Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gcash_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GCash Reference No.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='individual.individual', verbose_name='Payer (Main Individual)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='or_number',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='OR Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], default='cash', max_length=10, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending Validation (GCash)'), ('cancelled', 'Cancelled')], default='paid', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By'),
        ),
    ]
