# Generated by Django 4.2.23 on 2025-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_contributiontype_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Official Receipt (OR) number or internal reference.', max_length=100, null=True),
        ),
    ]
