# Generated by Django 4.2.23 on 2025-06-20 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution_type', '0001_initial'),
        ('individual', '0001_initial'),
        ('payment', '0003_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveredmember',
            options={'verbose_name': 'Miyembro nga Gi-cover', 'verbose_name_plural': 'Mga Miyembro nga Gi-cover'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-or_number'], 'verbose_name': 'Bayad', 'verbose_name_plural': 'Mga Bayad'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='church',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.AddField(
            model_name='coveredmember',
            name='amount_covered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kantidad nga Gi-cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kantidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coveredmember',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_payments', to='individual.individual', verbose_name='Miyembro nga Gi-cover'),
        ),
        migrations.AlterField(
            model_name='coveredmember',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='payment.payment', verbose_name='Bayad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rason sa Pagkansela'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Petsa sa Pag-kansela'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Gi-kansela ni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL, verbose_name='Gikolekta ni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contribution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contribution_type.contributiontype', verbose_name='Tipo sa Kontribusyon'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Gihimo niadtong'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Gihimo ni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Petsa sa Bayad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gcash_reference_number',
            field=models.CharField(blank=True, help_text='Required if Payment Method is GCash and needs validation.', max_length=100, null=True, verbose_name='GCash Reference Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='individual.individual', verbose_name='Nagbayad (Payer)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='or_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='OR Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], default='cash', max_length=10, verbose_name='Pamaagi sa Bayad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending (for GCash validation)'), ('cancelled', 'Cancelled')], default='paid', max_length=10, verbose_name='Status sa Bayad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Gi-update niadtong'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Gi-update ni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Petsa sa Pag-validate'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_validated', to=settings.AUTH_USER_MODEL, verbose_name='Gi-validate ni'),
        ),
    ]
