# Generated by Django 4.2.23 on 2025-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_VALIDATION', 'Pending Validation'), ('VALIDATED', 'Validated'), ('CANCELLED', 'Cancelled'), ('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('LEGACY', 'Legacy Record')], default='PENDING_VALIDATION', help_text='Current status of the payment (e.g., Pending Validation, Validated, Cancelled, Legacy).', max_length=20),
        ),
    ]
