# Generated by Django 4.2.23 on 2025-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='series_prefix',
            field=models.CharField(blank=True, help_text="Custom series prefix for the receipt number (e.g., 'KDM-'). If left blank, a date-based prefix 'OR-YYYY-MM-' will be used.", max_length=50, null=True),
        ),
    ]
